[package]
name = "popsicle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
crossterm = "0.26.1"
rand = "0.8.5"
tui = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
